### ISSUE TITLE
Console support?

### ISSUE THREAD

**Issue by ha-kuro** [alessandrofama/wwise-godot-integration#67]
Say we wanted to port a game to consoles using a third-party publisher like Pineapple Works, would there be configuration issues or anything?

In the Platform Selection there's only PC and Mobile options, so just wanted to check.

**Comment by alessandrofama** [comment]
Yes there will be configuration issues and getting Wwise running will require additional non trivial porting work.

For 3.x you need to do the following:
1) Make sure the GDNative module in the engine was ported to the desired platform.
2) Port the godot-cpp bindings for 3.x using the console SDK.
3) Get a license from Audiokinetic and download the their SDK.
4) Modify this integration and add support for the console platform.

As we are not affiliated with Audiokinetic nor with any console manufacturer, we can't provide any public support

**Comment by alessandrofama** [comment]
Yes, there will be configuration issues, and getting Wwise to work will require additional, non-trivial porting work.

For 3.x you need to do the following:
1) Make sure the GDNative module in the engine has been ported to the desired platform.
2) Port the godot-cpp bindings for 3.x using the console SDK.
3) Get a licence from Audiokinetic and download their SDK.
4) Modify this integration and add support for the console platform you want.

Since we are not affiliated with Autokinetic or any console manufacturer, and this integration is open source as opposed to proprietary console SDKs, we cannot offer public support for Wwise + consoles. Even if we had support for consoles, we would not be allowed to share the work in this repo.

If you or your porting studio need technical advice on the work required to port this integration, please feel free to contact me at me@alessandrofama.com.

**Comment by ha-kuro** [comment]
Thanks for the heads up and very much appreciate the support ♥
