### ISSUE TITLE
Error loading extension (Godot 4.0.4, Wwise 2022.1.6)

### ISSUE THREAD

**Issue by tdspk** [alessandrofama/wwise-godot-integration#80]
### Wwise integration version

wwise-2022.1.6-for-godot-4.0.4-stable-2.0

### System information

Windows 11

### Issue description

I wanted to test the integration on Godot 4.0.4. with Wwise 2022.1.6 and I'm getting these errors:

![image](https://github.com/alessandrofama/wwise-godot-integration/assets/8556403/68111772-87d1-4067-8e5c-53474c70e674)

The extension can't find the DLL:
![image](https://github.com/alessandrofama/wwise-godot-integration/assets/8556403/9a7b9562-2986-47cf-a670-f8ca6e4b6b21)

I checked the paths and the DLL is there.
I found some typos in the config file, corrected them, but still not working:

![image](https://github.com/alessandrofama/wwise-godot-integration/assets/8556403/2bcec033-0adc-48c5-84e0-6cf2b6c6ff5b)

Any thoughts on that?

### Steps to reproduce

Download Godot 4.0.4 and the corresponding Wwise zip. Follow the steps on the getting started guide.

### Minimal reproduction project

N/A

**Comment by alessandrofama** [comment]
Does this still happen on the latest release? 4.1 and 2023.1?

**Comment by tdspk** [comment]
I did not test yet, since I'm not working with Wwise beta. But can do!

**Comment by tdspk** [comment]
Worked fine with the latest release. Mind, the typos are still in the wwise.gdextension file.
I can use the latest versions, but there might be people who want to use a previous version.

Thanks! T

**Comment by alessandrofama** [comment]
The typos fix is already merged and will be available in the next release, although this will be only for 4.1+ and 2023.1.

To fix your issue you would want to install the MSVC C++-x64/x86-Buildtools. You can find them as a package in the Visual Studio Installer. For example the MSVC v142 - VS 2019 C++ Build Tools. Installing these usually resolves the error in loading the DLL. This is already fixed in the last release.

There are currently no plans to update the 4.0 release, but if your project is still on 4.0 I can think about preparing a patch release. Is there any possibility to upgrade to 4.1 for you?

**Comment by tdspk** [comment]
Did not have a minute to test, sorry! No need for a patch release, I'm just testing the possibilities. But there might be people who want one. We'll see! Thanks for the great work!
